-- Add more useful categories for financial tracking
INSERT INTO categories (name, type, icon, color) VALUES
-- Additional Expense Categories
('Loan Repayment', 'expense', 'CreditCard', '#dc2626'),
('Insurance', 'expense', 'Shield', '#7c3aed'),
('Utilities', 'expense', 'Zap', '#ea580c'),
('Electricity', 'expense', 'Lightbulb', '#facc15'),
('Water & Sewer', 'expense', 'Droplets', '#06b6d4'),
('Gas', 'expense', 'Flame', '#f97316'),
('Internet & Phone', 'expense', 'Wifi', '#3b82f6'),
('Transportation', 'expense', 'Car', '#10b981'),
('Fuel/Gas', 'expense', 'Fuel', '#ef4444'),
('Public Transport', 'expense', 'Bus', '#8b5cf6'),
('Healthcare', 'expense', 'Heart', '#f43f5e'),
('Education', 'expense', 'GraduationCap', '#06b6d4'),
('Entertainment', 'expense', 'Film', '#f59e0b'),
('Streaming Services', 'expense', 'Play', '#8b5cf6'),
('Dining Out', 'expense', 'Utensils', '#ef4444'),
('Travel', 'expense', 'Plane', '#10b981'),
('Rent', 'expense', 'Home', '#dc2626'),
('Mortgage', 'expense', 'Building', '#dc2626'),
('Gym/Fitness', 'expense', 'Dumbbell', '#059669'),
('Beauty & Personal Care', 'expense', 'Sparkles', '#ec4899'),
('Pet Care', 'expense', 'Heart', '#f97316'),
('Subscriptions', 'expense', 'RefreshCcw', '#6366f1'),
('Taxes', 'expense', 'Receipt', '#dc2626'),
('Bank Fees', 'expense', 'Building2', '#ef4444'),
('Charity/Donations', 'expense', 'Gift', '#10b981'),
('Emergency Fund', 'expense', 'Shield', '#dc2626'),

-- Additional Income Categories
('Investment Returns', 'income', 'TrendingUp', '#10b981'),
('Rental Income', 'income', 'Building', '#059669'),
('Side Hustle', 'income', 'Briefcase', '#3b82f6'),
('Freelance', 'income', 'Laptop', '#8b5cf6'),
('Bonus', 'income', 'Gift', '#f59e0b'),
('Tax Refund', 'income', 'Receipt', '#10b981'),
('Insurance Claim', 'income', 'Shield', '#06b6d4'),
('Cashback/Rewards', 'income', 'Award', '#f59e0b'),
('Interest Income', 'income', 'Percent', '#059669'),
('Pension', 'income', 'Clock', '#6366f1'),
('Government Benefits', 'income', 'Building2', '#3b82f6'),
('Gifts Received', 'income', 'Gift', '#ec4899');