// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahjwhbfuvdgyjnvnmttt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoandoYmZ1dmRneWpudm5tdHR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDA0ODUsImV4cCI6MjA2OTI3NjQ4NX0.IuceOUBb22DapGR0kpCPKa3YQ_C-P0f1RRXNV30x1gI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});